### ISSUE TITLE
Unified code generation CLI 

### ISSUE THREAD

**Issue by hidmic** [ros2/rosidl#565]
#### Feature description

Connected to https://github.com/ros2/rosidl/issues/560. Description and rationale to be found at https://github.com/ros2/design/pull/310.

#### Implementation considerations

- [x] Attempt to install Python entry points from `ament_cmake` packages (https://github.com/ament/ament_cmake/pull/316).
- [x] Add `rosidl_cli` package, with a basic `rosidl generate` CLI. (https://github.com/ros2/rosidl/pull/567)
- [x] Edit: Add `rosidl translate` CLI verb for interface definition conversion. (https://github.com/ros2/rosidl/pull/575)
- [x] Edit: Expose CLI as API. (https://github.com/ros2/rosidl/pull/577) 
   - Useful to e.g. perform implicit interface translation on generation. 
- [x] Edit: Provide `rosidl translate` plugins from existing adapter/generator packages:
   - [x] `rosidl_adapter` (https://github.com/ros2/rosidl/pull/576)
   - [x] `rosidl_generator_dds_idl` (https://github.com/ros2/rosidl_dds/pull/55)
- [x] Provide `rosidl generate` plugins from existing generator packages:
    - [x] `rosidl_generator_c` (#569)
    - [x] `rosidl_generator_cpp` (#570)
    - [x] `rosidl_generator_py` (https://github.com/ros2/rosidl_python/pull/123)
    - [x] `rosidl_typesupport_introspection_c` (#572)
    - [x] `rosidl_typesupport_introspection_cpp` (#573)
    - [x] `rosidl_typesupport_c` (https://github.com/ros2/rosidl_typesupport/pull/105)
    - [x] `rosidl_typesupport_cpp` (https://github.com/ros2/rosidl_typesupport/pull/104)
    - [x] `rosidl_typesupport_fastrtps_c` (https://github.com/ros2/rosidl_typesupport_fastrtps/pull/65)
    - [x] `rosidl_typesupport_fastrtps_cpp` (https://github.com/ros2/rosidl_typesupport_fastrtps/pull/66)
    - [x] `rosidl_typesupport_connext_c` (https://github.com/ros2/rosidl_typesupport_connext/pull/67)
    - [x] `rosidl_typesupport_connext_cpp` (https://github.com/ros2/rosidl_typesupport_connext/pull/68)
- [ ] (Nice to have) Migrate Python logic out of `rosidl_cmake` and  into a `rosidl_common` package. 
- [x] Iterate on https://github.com/ros2/design/pull/310 ~if need be~.

**Comment by sloretz** [comment]
@hidmic it looks like only a nice-to-have checkbox is unchecked. Is this ticket complete?
